### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MarisaKirisame**

### CODE REVIEW

**Comment by p16i** [comment]
There seem to be two typos in the declaration of CLI arguments.

1.  [Line 40-41](https://github.com/akamaster/pytorch_resnet_cifar10/blob/master/trainer.py#L40)
```
parser.add_argument('--weight-decay', '--wd', default=1e-4, type=float,
                    metavar='W', help='weight decay (default: 5e-4)')
```
The actual value is `1e-4` but what written in the help is `5e-4`.
2. [Line 42](https://github.com/akamaster/pytorch_resnet_cifar10/blob/master/trainer.py#L42)
```
parser.add_argument('--print-freq', '-p', default=50, type=int,
                    metavar='N', help='print frequency (default: 20)')
```
Similar issue as above. 

IMHO, we can fix them in this PR. @MarisaKirisame  what do you think?

**Comment by akamaster** [comment]
@MarisaKirisame @heytitle Thanks a lot for your comments. I think some of the issues were fixed, but not all. If you are willing to change/update your pull request this will be amazing! @heytitle, if @MarisaKirisame is not going to change the pull request, are you willing to create your own?

**Comment by MarisaKirisame** [comment]
@akamaster hi, I had fixed them.

**Review by akamaster — APPROVED** [review]
Thanks!

**Pull request merged**
